### ISSUE TITLE
Future plans

### ISSUE THREAD

**Issue by mamadaliev** [varkrift/bike-ground#1]
Hi, @varkrift! 
What plans do you have for the future and what to expect from this project?

**Comment by varkrift** [comment]
<b>Hi, @egnaf !</b>
<i>This is a training project. I plan to rewrite the code using the Vue.JS framework.</i>

**Comment by mamadaliev** [comment]
> Hi, @egnaf !
> This is a training project. I plan to rewrite the code using the Vue.JS framework.

Okay. Good Luck!
